greeting:
  message: "hello"

quarkus:
  http:
    port: 8088
  flyway:
    enabled: true
  datasource:
    db-kind: postgresql
    username: postgres
    password: admin
    jdbc:
      url: jdbc:postgresql://localhost:5432/compro
      min-size: 5
      max-size: 20
  smallrye-openapi:
    enable: true
  hibernate-orm:
    log:
      sql: true
      format-sql: true
      bind-parameters: true
      jdbc-warnings: true